import { useState, useCallback } from 'react';
import { useLocalStorage } from '../../lib/useLocalStorage';
import type { Lang } from '../../lib/i18n';
import styles from './ProjectTracker.module.css';

interface Phase {
  id: string;
  label: string;
  checkpoints: { id: string; text: string }[];
}

const PHASES: Phase[] = [
  {
    id: 'setup',
    label: 'Setup',
    checkpoints: [
      { id: 'gh-cli', text: 'GitHub CLI instalada e autenticada' },
      { id: 'gh-mcp', text: 'GitHub MCP configurado na ferramenta' },
    ],
  },
  {
    id: 'repo',
    label: 'Repositório',
    checkpoints: [
      { id: 'repo-created', text: 'Repositório criado no GitHub' },
      { id: 'repo-cloned', text: 'Repositório clonado localmente' },
    ],
  },
  {
    id: 'harness',
    label: 'Harness',
    checkpoints: [
      {
        id: 'harness-file',
        text: 'Arquivo de contexto criado (CLAUDE.md / AGENTS.md)',
      },
      { id: 'harness-reviewed', text: 'Arquivo revisado e faz sentido' },
    ],
  },
  {
    id: 'plan',
    label: 'Plano',
    checkpoints: [
      {
        id: 'plan-generated',
        text: 'Plano de implementação gerado pelo agente',
      },
      { id: 'plan-reviewed', text: 'Plano revisado e ajustado' },
      { id: 'plan-saved', text: 'Plano salvo no repositório' },
    ],
  },
  {
    id: 'build',
    label: 'Build',
    checkpoints: [
      { id: 'search-works', text: 'Busca de artistas funciona' },
      { id: 'discography-works', text: 'Discografia do artista carrega' },
      { id: 'album-works', text: 'Detalhes do álbum aparecem' },
      { id: 'runs-locally', text: 'Projeto roda localmente sem erros' },
    ],
  },
  {
    id: 'deploy',
    label: 'Deploy',
    checkpoints: [
      { id: 'gh-actions', text: 'GitHub Actions configurado' },
      { id: 'pages-live', text: 'Site publicado no GitHub Pages' },
      { id: 'site-works', text: 'Todas as funcionalidades no site publicado' },
    ],
  },
];

const PHASES_BY_LANG: Record<Lang, Phase[]> = {
  'pt-BR': PHASES,
  en: [
    {
      id: 'setup',
      label: 'Setup',
      checkpoints: [
        { id: 'gh-cli', text: 'GitHub CLI installed and authenticated' },
        { id: 'gh-mcp', text: 'GitHub MCP configured in your tool' },
      ],
    },
    {
      id: 'repo',
      label: 'Repository',
      checkpoints: [
        { id: 'repo-created', text: 'Repository created on GitHub' },
        { id: 'repo-cloned', text: 'Repository cloned locally' },
      ],
    },
    {
      id: 'harness',
      label: 'Harness',
      checkpoints: [
        {
          id: 'harness-file',
          text: 'Context file created (CLAUDE.md / AGENTS.md)',
        },
        { id: 'harness-reviewed', text: 'File reviewed and makes sense' },
      ],
    },
    {
      id: 'plan',
      label: 'Plan',
      checkpoints: [
        {
          id: 'plan-generated',
          text: 'Implementation plan generated by agent',
        },
        { id: 'plan-reviewed', text: 'Plan reviewed and adjusted' },
        { id: 'plan-saved', text: 'Plan saved in repository' },
      ],
    },
    {
      id: 'build',
      label: 'Build',
      checkpoints: [
        { id: 'search-works', text: 'Artist search works' },
        { id: 'discography-works', text: "Artist's discography loads" },
        { id: 'album-works', text: 'Album details show up' },
        { id: 'runs-locally', text: 'Project runs locally without errors' },
      ],
    },
    {
      id: 'deploy',
      label: 'Deploy',
      checkpoints: [
        { id: 'gh-actions', text: 'GitHub Actions configured' },
        { id: 'pages-live', text: 'Site published on GitHub Pages' },
        { id: 'site-works', text: 'All features working on published site' },
      ],
    },
  ],
};

const LABELS = {
  'pt-BR': {
    title: 'Seu progresso',
    phaseOf: (current: number, total: number) => `Fase ${current} de ${total}`,
    tabAria: 'Fases do projeto',
    previousAria: 'Fase anterior',
    nextAria: 'Próxima fase',
    resetAria: 'Limpar progresso',
    reset: 'Recomeçar',
    complete: 'Projeto concluído!',
  },
  en: {
    title: 'Your progress',
    phaseOf: (current: number, total: number) => `Phase ${current} of ${total}`,
    tabAria: 'Project phases',
    previousAria: 'Previous phase',
    nextAria: 'Next phase',
    resetAria: 'Reset progress',
    reset: 'Start over',
    complete: 'Project complete!',
  },
} as const;

interface Props {
  lang?: Lang;
}

export default function ProjectTracker({ lang = 'pt-BR' }: Props) {
  const [active, setActive] = useState(0);
  const [checked, setChecked] = useLocalStorage<Record<string, boolean>>(
    'ai-native-project-tracker',
    {},
  );

  const phases = PHASES_BY_LANG[lang];
  const labels = LABELS[lang];

  const toggleCheck = useCallback(
    (checkpointId: string) => {
      setChecked((prev) => ({
        ...prev,
        [checkpointId]: !prev[checkpointId],
      }));
    },
    [setChecked],
  );

  const isPhaseComplete = (phase: Phase) =>
    phase.checkpoints.every((cp) => checked[cp.id]);

  const totalCheckpoints = phases.reduce(
    (sum, p) => sum + p.checkpoints.length,
    0,
  );
  const checkedCount = phases.reduce(
    (sum, p) => sum + p.checkpoints.filter((cp) => checked[cp.id]).length,
    0,
  );
  const allComplete = checkedCount === totalCheckpoints;
  const progressPct = Math.round((checkedCount / totalCheckpoints) * 100);

  const handleReset = useCallback(() => {
    setChecked({});
    setActive(0);
  }, [setChecked]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        setActive((prev) => Math.min(prev + 1, phases.length - 1));
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        setActive((prev) => Math.max(prev - 1, 0));
      }
    },
    [phases.length],
  );

  const currentPhase = phases[active];

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h4 className={styles.title}>{labels.title}</h4>
        <span className={styles.counter}>
          {labels.phaseOf(active + 1, phases.length)}
        </span>
      </div>

      <div
        className={styles.progressBar}
        role="progressbar"
        aria-valuenow={progressPct}
        aria-valuemin={0}
        aria-valuemax={100}
      >
        <div
          className={styles.progressFill}
          style={{ width: `${progressPct}%` }}
        />
      </div>

      <div className={styles.stepperRow}>
        <button
          className={styles.navBtn}
          onClick={() => setActive((p) => Math.max(p - 1, 0))}
          disabled={active === 0}
          aria-label={labels.previousAria}
        >
          &larr;
        </button>

        <div
          className={styles.steps}
          role="tablist"
          aria-label={labels.tabAria}
          onKeyDown={handleKeyDown}
        >
          {phases.map((p, i) => (
            <button
              key={p.id}
              id={`project-tab-${i}`}
              role="tab"
              aria-selected={i === active}
              aria-controls={`project-panel-${i}`}
              aria-label={p.label}
              className={`${styles.step} ${i === active ? styles.stepActive : ''} ${isPhaseComplete(p) ? styles.stepDone : ''}`}
              onClick={() => setActive(i)}
              tabIndex={i === active ? 0 : -1}
            >
              <span className={styles.stepCircle}>
                {isPhaseComplete(p) ? '✓' : i + 1}
              </span>
              <span className={styles.stepLabel}>{p.label}</span>
            </button>
          ))}
        </div>

        <button
          className={styles.navBtn}
          onClick={() => setActive((p) => Math.min(p + 1, phases.length - 1))}
          disabled={active === phases.length - 1}
          aria-label={labels.nextAria}
        >
          &rarr;
        </button>
      </div>

      <div
        id={`project-panel-${active}`}
        role="tabpanel"
        aria-labelledby={`project-tab-${active}`}
        className={styles.panel}
      >
        <h4 className={styles.phaseTitle}>{currentPhase.label}</h4>
        <div className={styles.checkpoints}>
          {currentPhase.checkpoints.map((cp) => (
            <label key={cp.id} className={styles.checkItem}>
              <input
                type="checkbox"
                checked={!!checked[cp.id]}
                onChange={() => toggleCheck(cp.id)}
                className={styles.checkbox}
              />
              <span className={checked[cp.id] ? styles.checkedText : ''}>
                {cp.text}
              </span>
            </label>
          ))}
        </div>
      </div>

      {allComplete && (
        <div className={styles.completeCard}>
          <span className={styles.completeText}>{labels.complete}</span>
        </div>
      )}

      {checkedCount > 0 && (
        <button
          className={styles.resetBtn}
          onClick={handleReset}
          aria-label={labels.resetAria}
        >
          {labels.reset}
        </button>
      )}
    </div>
  );
}
