import type { Lang } from '../lib/i18n';
import { withBase, defaultLang, languages } from '../lib/i18n';

export interface ChapterCheckpoint {
  id: string;
  text: Record<Lang, string>;
}

export interface Chapter {
  number: number;
  id: string;
  title: Record<Lang, string>;
  shortLabel: Record<Lang, string>;
  description: Record<Lang, string>;
  slug: Record<Lang, string>;
  checkpoints: ChapterCheckpoint[];
  isReference?: boolean;
}

export const CHAPTERS: Chapter[] = [
  {
    number: 1,
    id: 'setup',
    title: {
      'pt-BR': 'Preparar o terreno',
      en: 'Set the ground',
    },
    shortLabel: {
      'pt-BR': 'Preparar',
      en: 'Setup',
    },
    description: {
      'pt-BR':
        'Instalar a GitHub CLI, criar o repositório e configurar o harness do projeto.',
      en: 'Install the GitHub CLI, create the repository, and set up the project harness.',
    },
    slug: {
      'pt-BR': 'preparar',
      en: 'setup',
    },
    checkpoints: [
      {
        id: 'gh-cli',
        text: {
          'pt-BR': 'GitHub CLI instalada e autenticada',
          en: 'GitHub CLI installed and authenticated',
        },
      },
      {
        id: 'repo-created',
        text: {
          'pt-BR': 'Repositório criado no GitHub',
          en: 'Repository created on GitHub',
        },
      },
      {
        id: 'harness-file',
        text: {
          'pt-BR': 'Arquivo de contexto (CLAUDE.md) criado e revisado',
          en: 'Context file (CLAUDE.md) created and reviewed',
        },
      },
    ],
  },
  {
    number: 2,
    id: 'plan',
    title: {
      'pt-BR': 'Planejar com o agente',
      en: 'Plan with the agent',
    },
    shortLabel: {
      'pt-BR': 'Planejar',
      en: 'Plan',
    },
    description: {
      'pt-BR':
        'Definir as funcionalidades, pedir um plano de implementação ao agente e revisar.',
      en: 'Define the features, ask the agent for an implementation plan, and review it.',
    },
    slug: {
      'pt-BR': 'planejar',
      en: 'plan',
    },
    checkpoints: [
      {
        id: 'plan-generated',
        text: {
          'pt-BR': 'Plano de implementação gerado pelo agente',
          en: 'Implementation plan generated by agent',
        },
      },
      {
        id: 'plan-reviewed',
        text: {
          'pt-BR': 'Plano revisado e ajustado por você',
          en: 'Plan reviewed and adjusted by you',
        },
      },
      {
        id: 'plan-saved',
        text: {
          'pt-BR': 'Plano salvo no repositório',
          en: 'Plan saved in the repository',
        },
      },
    ],
  },
  {
    number: 3,
    id: 'build',
    title: {
      'pt-BR': 'Construir por partes',
      en: 'Build in parts',
    },
    shortLabel: {
      'pt-BR': 'Construir',
      en: 'Build',
    },
    description: {
      'pt-BR':
        'Executar o plano fase a fase com SDD, resolver CORS e validar cada funcionalidade.',
      en: 'Execute the plan phase by phase with SDD, resolve CORS, and validate each feature.',
    },
    slug: {
      'pt-BR': 'construir',
      en: 'build',
    },
    checkpoints: [
      {
        id: 'search-works',
        text: {
          'pt-BR': 'Busca de artistas funciona',
          en: 'Artist search works',
        },
      },
      {
        id: 'discography-works',
        text: {
          'pt-BR': 'Discografia do artista carrega',
          en: "Artist's discography loads",
        },
      },
      {
        id: 'album-works',
        text: {
          'pt-BR': 'Detalhes do álbum aparecem',
          en: 'Album details show up',
        },
      },
      {
        id: 'runs-locally',
        text: {
          'pt-BR': 'Projeto roda localmente sem erros',
          en: 'Project runs locally without errors',
        },
      },
    ],
  },
  {
    number: 4,
    id: 'publish',
    title: {
      'pt-BR': 'Publicar',
      en: 'Publish',
    },
    shortLabel: {
      'pt-BR': 'Publicar',
      en: 'Publish',
    },
    description: {
      'pt-BR':
        'Fazer push, configurar GitHub Actions e validar o site publicado no GitHub Pages.',
      en: 'Push code, set up GitHub Actions, and validate the published site on GitHub Pages.',
    },
    slug: {
      'pt-BR': 'publicar',
      en: 'publish',
    },
    checkpoints: [
      {
        id: 'gh-actions',
        text: {
          'pt-BR': 'GitHub Actions configurado',
          en: 'GitHub Actions configured',
        },
      },
      {
        id: 'pages-live',
        text: {
          'pt-BR': 'Site publicado no GitHub Pages',
          en: 'Site published on GitHub Pages',
        },
      },
      {
        id: 'site-works',
        text: {
          'pt-BR': 'Todas as funcionalidades no site publicado',
          en: 'All features working on published site',
        },
      },
    ],
  },
  {
    number: 5,
    id: 'troubleshooting',
    title: {
      'pt-BR': 'Onde isso quebra',
      en: 'Where it breaks',
    },
    shortLabel: {
      'pt-BR': 'Debug',
      en: 'Debug',
    },
    description: {
      'pt-BR':
        'Referência rápida com os problemas mais comuns e como resolver cada um.',
      en: 'Quick reference for the most common problems and how to fix each one.',
    },
    slug: {
      'pt-BR': 'troubleshooting',
      en: 'troubleshooting',
    },
    checkpoints: [],
    isReference: true,
  },
];

export const TRACKABLE_CHAPTERS = CHAPTERS.filter((ch) => !ch.isReference);

export function getChapterHref(chapterNumber: number, lang: Lang): string {
  const chapter = CHAPTERS.find((ch) => ch.number === chapterNumber);
  if (!chapter) return '#';
  const prefix = lang === defaultLang ? '' : `${languages[lang].pathPrefix}/`;
  const projectSlug = lang === defaultLang ? 'projeto' : 'project';
  return withBase(`${prefix}${projectSlug}/${chapter.slug[lang]}`);
}

export function getChapterByNumber(num: number): Chapter | undefined {
  return CHAPTERS.find((ch) => ch.number === num);
}
