import type { Lang } from '../lib/i18n';
import { withBase, defaultLang, languages, getSessionHref } from '../lib/i18n';

export interface ChapterCheckpoint {
  id: string;
  text: Record<Lang, string>;
}

export interface ChapterReference {
  title: Record<Lang, string>;
  url: string | ((lang: Lang) => string);
  type: 'artigo' | 'documentacao' | 'talk' | 'video' | 'pesquisa';
  source: Record<Lang, string>;
}

export interface Chapter {
  number: number;
  id: string;
  title: Record<Lang, string>;
  shortLabel: Record<Lang, string>;
  description: Record<Lang, string>;
  slug: Record<Lang, string>;
  checkpoints: ChapterCheckpoint[];
  references: ChapterReference[];
  isReference?: boolean;
}

export const CHAPTERS: Chapter[] = [
  {
    number: 1,
    id: 'setup',
    title: {
      'pt-BR': 'Preparar o terreno',
      en: 'Set the ground',
    },
    shortLabel: {
      'pt-BR': 'Preparar',
      en: 'Setup',
    },
    description: {
      'pt-BR':
        'Instalar a GitHub CLI, criar o repositório e preparar README, PLAN.md e regras do agente.',
      en: 'Install the GitHub CLI, create the repository, and prepare README, PLAN.md, and agent rules.',
    },
    slug: {
      'pt-BR': 'preparar',
      en: 'setup',
    },
    checkpoints: [
      {
        id: 'gh-cli',
        text: {
          'pt-BR': 'GitHub CLI instalada e autenticada',
          en: 'GitHub CLI installed and authenticated',
        },
      },
      {
        id: 'repo-created',
        text: {
          'pt-BR': 'Repositório criado no GitHub',
          en: 'Repository created on GitHub',
        },
      },
      {
        id: 'harness-file',
        text: {
          'pt-BR': 'README, PLAN.md e regras do agente criados e revisados',
          en: 'README, PLAN.md, and agent rules created and reviewed',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'Ferramentas: IDEs vs CLI',
          en: 'Tools: IDEs vs CLI',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'ferramentas' : 'tools'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'Como operar de forma AI-native na prática',
          en: 'How to operate AI-native in practice',
        },
        url: (lang: Lang) =>
          getSessionHref(
            lang,
            lang === 'pt-BR' ? 'como-operar' : 'how-to-operate',
          ),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'GitHub CLI — Documentação oficial',
          en: 'GitHub CLI — Official docs',
        },
        url: 'https://cli.github.com/manual/',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
    ],
  },
  {
    number: 2,
    id: 'plan',
    title: {
      'pt-BR': 'Planejar com o agente',
      en: 'Plan with the agent',
    },
    shortLabel: {
      'pt-BR': 'Planejar',
      en: 'Plan',
    },
    description: {
      'pt-BR':
        'Definir as funcionalidades, pedir um plano de implementação ao agente e revisar.',
      en: 'Define the features, ask the agent for an implementation plan, and review it.',
    },
    slug: {
      'pt-BR': 'planejar',
      en: 'plan',
    },
    checkpoints: [
      {
        id: 'plan-generated',
        text: {
          'pt-BR': 'Plano de implementação gerado pelo agente',
          en: 'Implementation plan generated by agent',
        },
      },
      {
        id: 'plan-reviewed',
        text: {
          'pt-BR': 'Plano revisado e ajustado por você',
          en: 'Plan reviewed and adjusted by you',
        },
      },
      {
        id: 'plan-saved',
        text: {
          'pt-BR': 'Plano salvo no repositório',
          en: 'Plan saved in the repository',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'A evolução do desenvolvimento com IA',
          en: 'How AI development matured',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'maturidade' : 'maturity'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'Como operar de forma AI-native na prática',
          en: 'How to operate AI-native in practice',
        },
        url: (lang: Lang) =>
          getSessionHref(
            lang,
            lang === 'pt-BR' ? 'como-operar' : 'how-to-operate',
          ),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'Deezer API — Documentação',
          en: 'Deezer API — Documentation',
        },
        url: 'https://developers.deezer.com/api',
        type: 'documentacao',
        source: { 'pt-BR': 'Deezer', en: 'Deezer' },
      },
    ],
  },
  {
    number: 3,
    id: 'build',
    title: {
      'pt-BR': 'Construir por partes',
      en: 'Build in parts',
    },
    shortLabel: {
      'pt-BR': 'Construir',
      en: 'Build',
    },
    description: {
      'pt-BR':
        'Executar o plano fase a fase com SDD, resolver CORS e validar cada funcionalidade.',
      en: 'Execute the plan phase by phase with SDD, resolve CORS, and validate each feature.',
    },
    slug: {
      'pt-BR': 'construir',
      en: 'build',
    },
    checkpoints: [
      {
        id: 'search-works',
        text: {
          'pt-BR': 'Busca de artistas funciona',
          en: 'Artist search works',
        },
      },
      {
        id: 'discography-works',
        text: {
          'pt-BR': 'Discografia do artista carrega',
          en: "Artist's discography loads",
        },
      },
      {
        id: 'album-works',
        text: {
          'pt-BR': 'Detalhes do álbum aparecem',
          en: 'Album details show up',
        },
      },
      {
        id: 'runs-locally',
        text: {
          'pt-BR': 'Projeto roda localmente sem erros',
          en: 'Project runs locally without errors',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'A evolução do desenvolvimento com IA',
          en: 'How AI development matured',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'maturidade' : 'maturity'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'Cross-Origin Resource Sharing (CORS)',
          en: 'Cross-Origin Resource Sharing (CORS)',
        },
        url: 'https://developer.mozilla.org/docs/Web/HTTP/CORS',
        type: 'documentacao',
        source: { 'pt-BR': 'MDN Web Docs', en: 'MDN Web Docs' },
      },
      {
        title: {
          'pt-BR': 'Deezer API — Documentação',
          en: 'Deezer API — Documentation',
        },
        url: 'https://developers.deezer.com/api',
        type: 'documentacao',
        source: { 'pt-BR': 'Deezer', en: 'Deezer' },
      },
    ],
  },
  {
    number: 4,
    id: 'publish',
    title: {
      'pt-BR': 'Publicar',
      en: 'Publish',
    },
    shortLabel: {
      'pt-BR': 'Publicar',
      en: 'Publish',
    },
    description: {
      'pt-BR':
        'Fazer push, configurar GitHub Actions e validar o site publicado no GitHub Pages.',
      en: 'Push code, set up GitHub Actions, and validate the published site on GitHub Pages.',
    },
    slug: {
      'pt-BR': 'publicar',
      en: 'publish',
    },
    checkpoints: [
      {
        id: 'gh-actions',
        text: {
          'pt-BR': 'GitHub Actions configurado',
          en: 'GitHub Actions configured',
        },
      },
      {
        id: 'pages-live',
        text: {
          'pt-BR': 'Site publicado no GitHub Pages',
          en: 'Site published on GitHub Pages',
        },
      },
      {
        id: 'site-works',
        text: {
          'pt-BR': 'Todas as funcionalidades no site publicado',
          en: 'All features working on published site',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'Como operar de forma AI-native na prática',
          en: 'How to operate AI-native in practice',
        },
        url: (lang: Lang) =>
          getSessionHref(
            lang,
            lang === 'pt-BR' ? 'como-operar' : 'how-to-operate',
          ),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'GitHub Pages — Documentação',
          en: 'GitHub Pages — Documentation',
        },
        url: 'https://docs.github.com/pages',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
      {
        title: {
          'pt-BR': 'GitHub Actions — Documentação',
          en: 'GitHub Actions — Documentation',
        },
        url: 'https://docs.github.com/actions',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
    ],
  },
  {
    number: 5,
    id: 'troubleshooting',
    title: {
      'pt-BR': 'Onde isso quebra',
      en: 'Where it breaks',
    },
    shortLabel: {
      'pt-BR': 'Debug',
      en: 'Debug',
    },
    description: {
      'pt-BR':
        'Referência rápida com os problemas mais comuns e como resolver cada um.',
      en: 'Quick reference for the most common problems and how to fix each one.',
    },
    slug: {
      'pt-BR': 'troubleshooting',
      en: 'troubleshooting',
    },
    checkpoints: [],
    references: [
      {
        title: {
          'pt-BR': 'Cross-Origin Resource Sharing (CORS)',
          en: 'Cross-Origin Resource Sharing (CORS)',
        },
        url: 'https://developer.mozilla.org/docs/Web/HTTP/CORS',
        type: 'documentacao',
        source: { 'pt-BR': 'MDN Web Docs', en: 'MDN Web Docs' },
      },
      {
        title: {
          'pt-BR': 'LLMs e os modelos mais usados',
          en: 'LLMs and the models people actually use',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'modelos' : 'models'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineering',
          en: 'AI-Native Engineering',
        },
      },
      {
        title: {
          'pt-BR': 'GitHub Actions — Documentação',
          en: 'GitHub Actions — Documentation',
        },
        url: 'https://docs.github.com/actions',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
    ],
    isReference: true,
  },
];

export const TRACKABLE_CHAPTERS = CHAPTERS.filter((ch) => !ch.isReference);

export function getChapterHref(chapterNumber: number, lang: Lang): string {
  const chapter = CHAPTERS.find((ch) => ch.number === chapterNumber);
  if (!chapter) return '#';
  const prefix = lang === defaultLang ? '' : `${languages[lang].pathPrefix}/`;
  const projectSlug = lang === defaultLang ? 'projeto' : 'project';
  return withBase(`${prefix}${projectSlug}/${chapter.slug[lang]}`);
}

export function getChapterByNumber(num: number): Chapter | undefined {
  return CHAPTERS.find((ch) => ch.number === num);
}

export interface ResolvedReference {
  id: string;
  title: string;
  url: string;
  type: 'artigo' | 'documentacao' | 'talk' | 'video' | 'pesquisa';
  source: string;
  category: string;
}

export function resolveChapterReferences(
  chapter: Chapter,
  lang: Lang,
): ResolvedReference[] {
  return chapter.references.map((ref, i) => ({
    id: `${chapter.id}-ref-${i}`,
    title: ref.title[lang],
    url: typeof ref.url === 'string' ? ref.url : ref.url(lang),
    type: ref.type,
    source: ref.source[lang],
    category: chapter.id,
  }));
}
