import type { Lang } from '../lib/i18n';
import { withBase, defaultLang, languages, getSessionHref } from '../lib/i18n';

export interface ChapterCheckpoint {
  id: string;
  text: Record<Lang, string>;
}

export interface ChapterReference {
  title: Record<Lang, string>;
  url: string | ((lang: Lang) => string);
  type: 'artigo' | 'documentacao' | 'talk' | 'video' | 'pesquisa';
  source: Record<Lang, string>;
}

export interface Chapter {
  number: number;
  id: string;
  title: Record<Lang, string>;
  shortLabel: Record<Lang, string>;
  description: Record<Lang, string>;
  slug: Record<Lang, string>;
  checkpoints: ChapterCheckpoint[];
  references: ChapterReference[];
  isReference?: boolean;
}

export const CHAPTERS: Chapter[] = [
  {
    number: 1,
    id: 'setup',
    title: {
      'pt-BR': 'Preparar o terreno',
      en: 'Set the ground',
    },
    shortLabel: {
      'pt-BR': 'Preparar',
      en: 'Setup',
    },
    description: {
      'pt-BR':
        'Criar o repositório no GitHub, clonar no terminal, abrir na ferramenta e preparar AGENTS.md, PLAN.md e README.md.',
      en: 'Create the repository on GitHub, clone it in the terminal, open it in your tool, and prepare AGENTS.md, PLAN.md, and README.md.',
    },
    slug: {
      'pt-BR': 'preparar',
      en: 'setup',
    },
    checkpoints: [
      {
        id: 'repo-created-manual',
        text: {
          'pt-BR': 'Repositório criado manualmente no GitHub',
          en: 'Repository created manually on GitHub',
        },
      },
      {
        id: 'repo-cloned-opened',
        text: {
          'pt-BR': 'Repositório clonado no terminal e aberto na ferramenta',
          en: 'Repository cloned in the terminal and opened in the tool',
        },
      },
      {
        id: 'setup-docs-created',
        text: {
          'pt-BR': 'AGENTS.md, PLAN.md e README.md criados e revisados',
          en: 'AGENTS.md, PLAN.md, and README.md created and reviewed',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'Ferramentas e modelos',
          en: 'Tools and models',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'ferramentas' : 'tools'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineers',
          en: 'AI-Native Engineers',
        },
      },
      {
        title: {
          'pt-BR': 'SDD e Harness Design',
          en: 'SDD and Harness Design',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'maturidade' : 'maturity'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineers',
          en: 'AI-Native Engineers',
        },
      },
      {
        title: {
          'pt-BR': 'GitHub Docs: criar um novo repositório',
          en: 'GitHub Docs: create a new repository',
        },
        url: 'https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
      {
        title: {
          'pt-BR': 'Git: documentação do comando clone',
          en: 'Git: clone command documentation',
        },
        url: 'https://git-scm.com/docs/git-clone',
        type: 'documentacao',
        source: { 'pt-BR': 'Git', en: 'Git' },
      },
      {
        title: {
          'pt-BR': 'GitHub CLI quickstart',
          en: 'GitHub CLI quickstart',
        },
        url: 'https://docs.github.com/en/github-cli/github-cli/quickstart',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
      {
        title: {
          'pt-BR': 'Deezer API, documentação oficial',
          en: 'Deezer API, official documentation',
        },
        url: 'https://developers.deezer.com/api',
        type: 'documentacao',
        source: { 'pt-BR': 'Deezer', en: 'Deezer' },
      },
    ],
  },
  {
    number: 2,
    id: 'plan',
    title: {
      'pt-BR': 'Planejar com o agente',
      en: 'Plan with the agent',
    },
    shortLabel: {
      'pt-BR': 'Planejar',
      en: 'Plan',
    },
    description: {
      'pt-BR':
        'Definir as funcionalidades, pedir um plano de implementação ao agente e revisar.',
      en: 'Define the features, ask the agent for an implementation plan, and review it.',
    },
    slug: {
      'pt-BR': 'planejar',
      en: 'plan',
    },
    checkpoints: [
      {
        id: 'plan-generated',
        text: {
          'pt-BR': 'Plano de implementação gerado pelo agente',
          en: 'Implementation plan generated by agent',
        },
      },
      {
        id: 'plan-reviewed',
        text: {
          'pt-BR': 'Plano revisado e ajustado por você',
          en: 'Plan reviewed and adjusted by you',
        },
      },
      {
        id: 'plan-saved',
        text: {
          'pt-BR': 'Plano salvo no repositório',
          en: 'Plan saved in the repository',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'SDD e Harness Design',
          en: 'SDD and Harness Design',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'maturidade' : 'maturity'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineers',
          en: 'AI-Native Engineers',
        },
      },
      {
        title: {
          'pt-BR': 'Deezer API, Documentação',
          en: 'Deezer API, Documentation',
        },
        url: 'https://developers.deezer.com/api',
        type: 'documentacao',
        source: { 'pt-BR': 'Deezer', en: 'Deezer' },
      },
    ],
  },
  {
    number: 3,
    id: 'build',
    title: {
      'pt-BR': 'Construir por partes',
      en: 'Build in parts',
    },
    shortLabel: {
      'pt-BR': 'Construir',
      en: 'Build',
    },
    description: {
      'pt-BR':
        'Começar pela phase 1 e executar o implementation plan phase por phase com um loop claro: PRD, PLAN mode, implementação, validação e report.',
      en: 'Start with phase 1 and execute the implementation plan phase by phase with a clear loop: PRD, PLAN mode, implementation, validation, and report.',
    },
    slug: {
      'pt-BR': 'construir',
      en: 'build',
    },
    checkpoints: [
      {
        id: 'phases-reviewed',
        text: {
          'pt-BR':
            'As phases do implementation plan foram revisadas e refinadas',
          en: 'The implementation plan phases were reviewed and refined',
        },
      },
      {
        id: 'phases-executed',
        text: {
          'pt-BR': 'As phases foram executadas e validadas uma por vez',
          en: 'The phases were executed and validated one by one',
        },
      },
      {
        id: 'phase-reports-saved',
        text: {
          'pt-BR':
            'Cada phase concluída gerou report e o projeto roda localmente',
          en: 'Each completed phase produced a report and the project runs locally',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'SDD e Harness Design',
          en: 'SDD and Harness Design',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'maturidade' : 'maturity'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineers',
          en: 'AI-Native Engineers',
        },
      },
      {
        title: {
          'pt-BR': 'Cross-Origin Resource Sharing (CORS)',
          en: 'Cross-Origin Resource Sharing (CORS)',
        },
        url: 'https://developer.mozilla.org/docs/Web/HTTP/CORS',
        type: 'documentacao',
        source: { 'pt-BR': 'MDN Web Docs', en: 'MDN Web Docs' },
      },
      {
        title: {
          'pt-BR': 'Deezer API, Documentação',
          en: 'Deezer API, Documentation',
        },
        url: 'https://developers.deezer.com/api',
        type: 'documentacao',
        source: { 'pt-BR': 'Deezer', en: 'Deezer' },
      },
    ],
  },
  {
    number: 4,
    id: 'publish',
    title: {
      'pt-BR': 'Publicar',
      en: 'Publish',
    },
    shortLabel: {
      'pt-BR': 'Publicar',
      en: 'Publish',
    },
    description: {
      'pt-BR':
        'Fazer push, configurar GitHub Actions e validar o site publicado no GitHub Pages.',
      en: 'Push code, set up GitHub Actions, and validate the published site on GitHub Pages.',
    },
    slug: {
      'pt-BR': 'publicar',
      en: 'publish',
    },
    checkpoints: [
      {
        id: 'gh-actions',
        text: {
          'pt-BR': 'GitHub Actions configurado',
          en: 'GitHub Actions configured',
        },
      },
      {
        id: 'pages-live',
        text: {
          'pt-BR': 'Site publicado no GitHub Pages',
          en: 'Site published on GitHub Pages',
        },
      },
      {
        id: 'site-works',
        text: {
          'pt-BR': 'Todas as funcionalidades no site publicado',
          en: 'All features working on published site',
        },
      },
    ],
    references: [
      {
        title: {
          'pt-BR': 'SDD e Harness Design',
          en: 'SDD and Harness Design',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'maturidade' : 'maturity'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineers',
          en: 'AI-Native Engineers',
        },
      },
      {
        title: {
          'pt-BR': 'GitHub Pages, Documentação',
          en: 'GitHub Pages, Documentation',
        },
        url: 'https://docs.github.com/pages',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
      {
        title: {
          'pt-BR': 'GitHub Actions, Documentação',
          en: 'GitHub Actions, Documentation',
        },
        url: 'https://docs.github.com/actions',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
    ],
  },
  {
    number: 5,
    id: 'troubleshooting',
    title: {
      'pt-BR': 'Onde isso quebra',
      en: 'Where it breaks',
    },
    shortLabel: {
      'pt-BR': 'Debug',
      en: 'Debug',
    },
    description: {
      'pt-BR':
        'Referência rápida com os problemas mais comuns e como resolver cada um.',
      en: 'Quick reference for the most common problems and how to fix each one.',
    },
    slug: {
      'pt-BR': 'troubleshooting',
      en: 'troubleshooting',
    },
    checkpoints: [],
    references: [
      {
        title: {
          'pt-BR': 'Cross-Origin Resource Sharing (CORS)',
          en: 'Cross-Origin Resource Sharing (CORS)',
        },
        url: 'https://developer.mozilla.org/docs/Web/HTTP/CORS',
        type: 'documentacao',
        source: { 'pt-BR': 'MDN Web Docs', en: 'MDN Web Docs' },
      },
      {
        title: {
          'pt-BR': 'Ferramentas e modelos',
          en: 'Tools and models',
        },
        url: (lang: Lang) =>
          getSessionHref(lang, lang === 'pt-BR' ? 'ferramentas' : 'tools'),
        type: 'artigo',
        source: {
          'pt-BR': 'AI-Native Engineers',
          en: 'AI-Native Engineers',
        },
      },
      {
        title: {
          'pt-BR': 'GitHub Actions, Documentação',
          en: 'GitHub Actions, Documentation',
        },
        url: 'https://docs.github.com/actions',
        type: 'documentacao',
        source: { 'pt-BR': 'GitHub', en: 'GitHub' },
      },
    ],
    isReference: true,
  },
];

export const TRACKABLE_CHAPTERS = CHAPTERS.filter((ch) => !ch.isReference);

export function getChapterHref(chapterNumber: number, lang: Lang): string {
  const chapter = CHAPTERS.find((ch) => ch.number === chapterNumber);
  if (!chapter) return '#';
  const prefix = lang === defaultLang ? '' : `${languages[lang].pathPrefix}/`;
  const projectSlug = lang === defaultLang ? 'projeto' : 'project';
  return withBase(`${prefix}${projectSlug}/${chapter.slug[lang]}`);
}

export function getChapterByNumber(num: number): Chapter | undefined {
  return CHAPTERS.find((ch) => ch.number === num);
}

export interface ResolvedReference {
  id: string;
  title: string;
  url: string;
  type: 'artigo' | 'documentacao' | 'talk' | 'video' | 'pesquisa';
  source: string;
  category: string;
}

export function resolveChapterReferences(
  chapter: Chapter,
  lang: Lang,
): ResolvedReference[] {
  return chapter.references.map((ref, i) => ({
    id: `${chapter.id}-ref-${i}`,
    title: ref.title[lang],
    url: typeof ref.url === 'string' ? ref.url : ref.url(lang),
    type: ref.type,
    source: ref.source[lang],
    category: chapter.id,
  }));
}
